export const project = [
  {
    id: 1,
    img: "./Advice.png",
    title: "Advice Box",
    lang: "ReactJS,TailwindCSS & Advice Pill API",
    github: "https://github.com/OlaiwonAbdullahi/Advice-Box",
    liveLink: "https://advice-box.netlify.app/",
  },
  {
    id: 2,
    img: "./SwyftPay.png",
    title: "Swyft Pay Website Clone",
    lang: "ReactJS & TailwindCSS",
    github: "https://github.com/OlaiwonAbdullahi/SwyftPay-Replicate",
    liveLink: "https://swyftpay-replicate.brimble.app/",
  },
  {
    id: 3,
    img: "./Wagmi-AI.png",
    title: "Wagmi AI ChatBot",
    lang: "HTML5, CSS3, JavaScript & Gemini API",
    github: "https://github.com/OlaiwonAbdullahi/Team-Wagmi-AI/",
    liveLink: "https://team-wagmi-ai.netlify.app/",
  },
  {
    id: 4,
    img: "./KryptoSkool.png",
    title: "Krypto Skool Landing Page",
    lang: "HTML/CSS, JavaScript, Bootstrap & AOS",
    github: "https://github.com/OlaiwonAbdullahi/Krypto-Skool",
    liveLink: "https://krypto-skool.netlify.app/",
  },
  {
    id: 5,
    img: "./Unity.png",
    title: "Unity High School Website",
    lang: "HTML/CSS, JavaScript, Bootstrap & AOS",
    github: "https://github.com/OlaiwonAbdullahi/UHSijokoota-website",
    liveLink: "https://unityhighschoolijokoota.netlify.app/",
  },
  {
    id: 6,
    img: "./nft-store.png",
    title: "NFT Store Landing Page",
    lang: "ReactJS & TailwindCSS",
    github: "https://github.com/OlaiwonAbdullahi/NFT-Mini-Store",
    liveLink: "https://abdul-nft-mini-store.netlify.app/",
  },
  {
    id: 7,
    img: "./qrcode.png",
    title: "QR Code Generator & Scanner",
    lang: "ReactJS, TailwindCSS & QR Code Package",
    github: "https://github.com/OlaiwonAbdullahi/QR-Scanner-generator",
    liveLink: "https://qr-scanner-generator.netlify.app/",
  },
  {
    id: 8,
    img: "./portfolio.png",
    title: "My Portfolio",
    lang: "ReactJS, TailwindCSS & AOS",
    github: "https://github.com/OlaiwonAbdullahi/Portfolio-V2",
    liveLink: "https://qr-scanner-generator.netlify.app/",
  },
];
