export const project = [
  {
    id: 1,
    img: "./assets/Advice.png",
    title: "Advice Box",
    lang: "React Js & Tailwind Css",
    github: "https://github.com/OlaiwonAbdullahi/Advice-Box",
    liveLink: "https://advice-box.netlify.app/",
  },
  {
    id: 2,
    img: "./assets/SwyftPay.png",
    title: "Swyft Pay",
    lang: "React Js & Tailwind Css",
    github: "https://github.com/OlaiwonAbdullahi/SwyftPay-Replicate",
    liveLink: "https://swyftpay-replicate.brimble.app/",
  },
  {
    id: 3,
    img: "./assets/KryptoSkool.png",
    title: "Krypto Skool",
    lang: "HTML/CSS , JS , Bootsrap",
    github: "https://github.com/OlaiwonAbdullahi/Krypto-Skool",
    liveLink: "https://krypto-skool.netlify.app/",
  },
  {
    id: 4,
    img: "./assets/unity.png",
    title: "Unity High SChool Ijoko Ota Website",
    lang: "HTML/CSS , JS , Bootsrap",
    github: "https://github.com/OlaiwonAbdullahi/UHSijokoota-website",
    liveLink: "https://unityhighschoolijokoota.netlify.app/",
  },
  {
    id: 5,
    img: "./assets/nft-store.png",
    title: "NFT Store Landing Page",
    lang: "React Js & Tailwind Css",
    github: "https://github.com/OlaiwonAbdullahi/NFT-Mini-Store",
    liveLink: "https://abdul-nft-mini-store.netlify.app/",
  },
  {
    id: 6,
    img: "./assets/qrcode.png",
    title: "QR Code Generator & Scanner",
    lang: "React Js ,Tailwind Css & QR Code Package",
    github: "https://github.com/OlaiwonAbdullahi/QR-Scanner-generator",
    liveLink: "https://qr-scanner-generator.netlify.app/",
  },
];
